tables:
  votes:
    id:
      sqlite: "INTEGER PRIMARY KEY AUTOINCREMENT"
      mysql: "INTEGER PRIMARY KEY AUTO_INCREMENT"
    player_uuid: "VARCHAR(36) NOT NULL"
    player_name: "VARCHAR(16) NOT NULL"
    vote_service: "VARCHAR(100) NOT NULL"
    vote_ts: "TIMESTAMP NOT NULL"
  players:
    player_uuid: "VARCHAR(36) PRIMARY KEY"
    player_name: "VARCHAR(16) NOT NULL"
    last_seen_ts: "TIMESTAMP NOT NULL"
  offline_rewards:
    player_uuid: "VARCHAR(36) NOT NULL"
    reward_id: "VARCHAR(255) NOT NULL"
    vote_service: "VARCHAR(255) NOT NULL"
    reward_ts: "TIMESTAMP NOT NULL"